### ISSUE TITLE
All activities need to open in a window

### ISSUE THREAD

**Issue by davegraham92120** [karbonfm/karbonfm#105]
Currently, most activities open in card windows. Since we need to open the discussion subscribers in a card window, the activity windows can't be cards.

**Comment by mr-scott** [comment]
We are using John Renfrew's "Machine-In-The-Middle" technique for this condition:
https://www.linkedin.com/pulse/machine-in-the-middle-model-filemaker-development-john-renfrew/

**Comment by davegraham92120** [comment]
There are many ways to accomplish multiple cards, however for Karbon we aim to keep things simple and employ as few workarounds as necessary. We also gain the additional benefit of allowing the activity windows to be resized and moved independently of the parent layout, which is often necessary. For instance, if I'm using the Meeting to log my minutes, I would want it to be much larger, and be able to reference related contacts and information from an Opportunity record.
