### ISSUE TITLE
Why Insert Calculated Result over Set Variable

### ISSUE THREAD

**Issue by marcoaperez** [karbonfm/karbonfm#120]
Maybe I have missed the point but in the Generator it has changed to ICR. Why is that?

"Included Set Variable code in Insert Calculated Result custom function for the folks who prefer SV over ICR."

This is not an issue, but I don't know where to place this question.

Thanks

**Comment by davegraham92120** [comment]
Insert Calculated Result can set variables, append to variables and more. I’m addition, you can click on the expression and go right into the editor; with Set Variable you have to first get past the useless dialog to get to the calculation editor.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
