### ISSUE TITLE
Karbon - 0.9.3.zip is missing 3 files

### ISSUE THREAD

**Issue by alecgregory** [karbonfm/karbonfm#18]
Three files are referenced as external data sources in karbon_kontacts.fmp12 but not in the zip package

- BoB.fmp12
- karbon_dev.fmp12
- karbon_konnector.fmp12

**Comment by toddgeist** [comment]
duplicate #17

**Comment by toddgeist** [comment]
Bob probable shouldn't be in there.  But the other two may need to be for now.

**Comment by alecgregory** [comment]
Can we copy karbon_konnector from the 0.9.2 zip?

**Comment by davegraham92120** [comment]
I pulled it because konnector in its current state is very specific to our internal workflow. We will be adding a receiver module soon, which is much better solution to managing incoming HTTP data. For now, I've added a placeholder file to prevent the error messages. See 0.9.4.
