### ISSUE TITLE
Build releases with Travis CI

### ISSUE THREAD

**Issue by jmbwell** [karbonfm/karbonfm#19]
For your consideration:

Each time a .zip file is added to the root of the repository (as with the 0.x.x.zip files), the size of the repo permanently grows, for everyone cloning the repo. This multiplies the size of the repo with each commit, and it won't hold up for long.

Github and TravisCI can build .zip files automatically and keep those files out of your repo. This project should consider using that facility.

I can't personally integrate your repo because of the permissions and setup required, but I've implemented it my fork (https://github.com/jmbwell/karbonfm) as an example. You can see the results if you click on "Releases" (https://github.com/jmbwell/karbonfm/releases). Each release includes links to download a .zip or a .tar.gz of the entire repo, along with a .zip file created just from the Files folder.

In the example setup, Travis only builds a new release when a commit is tagged. In this case, pushing a tag to the repo with the name of the release (such as "0.9.5a") will cause a release to be built with that name. Other commits and pushes will trigger a build, but not a release.

Integration involves creating a TravisCI account, giving it access to the repo, and then committing a `.travis.yml` file to the repo. Here's the one from my fork:

https://github.com/jmbwell/karbonfm/blob/master/.travis.yml

With the .fmp12 files already binaries that will inevitably take up space (possible git-lfs adoption notwithstanding), I would argue it's especially important to avoid pumping .zip blobs into the repo, and TravisCI is a free way to do so.

I might suggest also renaming the "Files" folder to "KarbonFM" so that it's clear what it is when the archive expands on the user's computer.

And finally, with all of this done, it's less important to put the name of the release in the filenames of any files or directories themselves, as Github automatically keeps version history, so users can simply download the latest or they can browse the history to download a prior release. Either way, all they have to worry about is finding a folder named "KarbonFM."

**Comment by davegraham92120** [comment]
Couldn't agree more. I had to push it out because the project was already delayed. We'll probably implement the process exactly as you described. Thanks so much for such a great description!

**Comment by davegraham92120** [comment]
Done. Thanks again for the help!
