### ISSUE TITLE
Incorrect versioning system explanatory comment

### ISSUE THREAD

**Issue by alecgregory** [karbonfm/karbonfm#20]
The Karbon.fmp12 file holds version information in the field meta::KarbonVersion. This is an unstored calc field. However, the comment in the field states that it is a global calc.

The final paragraph of the comment for the KarbonVersion field should read:

`This value must be updated manually and is stored in **an unstored** calc field to ensure that the version survives cloning and isn't cleared during migration to a production system.`

**Comment by davegraham92120** [comment]
I'll fix the the description. See #21 for the reason.

**Comment by davegraham92120** [comment]
Done. It will be in the next build.
