### ISSUE TITLE
Using next serial value for versioning

### ISSUE THREAD

**Issue by alecgregory** [karbonfm/karbonfm#21]
The Set Karbon Version script in Karbon.fmp12 suggests that you are considering a using a serial number based versioning system. I would support this as it allows automation of version changes and is more in line with the Karbon Manifesto than the unstored calculation method.

**Comment by davegraham92120** [comment]
We used to, but serial numbers are no longer safe since the release of the FM data migration tool. I tried everything under the sun and couldn't find another area of metadata to stuff the version so that it persists after a migration.
