### ISSUE TITLE
Record lock on user record throws an error that user record doesn't exist

### ISSUE THREAD

**Issue by davegraham92120** [karbonfm/karbonfm#26]
If I log into Karbon on one machine, leaving the user record locked, and I try to log into Karbon from another computer I'll get this alert during startup: 

![screen shot 2018-08-18 at 10 51 39 am](https://user-images.githubusercontent.com/20668953/44301938-bea43880-a2d4-11e8-8e61-0ef9f7a4ad98.png)

I'm thinking that we shouldn't throw that error if the user record couldn't be found.

**Comment by lancebrandenberg** [comment]
Fixed on Development.
