### ISSUE TITLE
Support container data

### ISSUE THREAD

**Issue by davegraham92120** [karbonfm/karbonfm#29]
Add File and FileAttachment tables based on QBO.

**Comment by bcooney93** [comment]
Completed.

**Comment by davegraham92120** [comment]
Please add to karbon_Build and reference this GH issue. 

Example: did this and that (GH #29)

**Comment by davegraham92120** [comment]
@bcooney93 - I don't see a record in karbon_Build!

**Comment by bcooney93** [comment]
OK, added record in Builder.
