### ISSUE TITLE
Use underscores instead of periods used for namespacing

### ISSUE THREAD

**Issue by alecgregory** [karbonfm/karbonfm#32]
Many variables and custom functions in Karbon appear to be namespaced. For example
```
JSON.ArrayConcat
JSON.ArrayFromRelated
```
I propose using underscores instead.

The reasons for this are:
1. [Strings with periods are not parsable keys for FileMaker's JSON functions](https://community.filemaker.com/message/709583?commentID=709583#comment-709583)
This isn't necessarily a problem right now, but in future, we may be able to automate creation and management of many FileMaker elements including custom functions and script creation. Having JSON key safe names for variables and custom functions could prevent a lot of issues with automated code creation in the future. As "Write code that Writes code" is in the Karbon manifesto, I think we should be mindful of how Karbon systems can be prepared to support this. I'd say this means keeping naming as consistent and compatible as possible.

**2. Dots suggest objects, but custom functions and variables aren't objects**
This is more obscure but with JavaScript playing a bigger part in FileMaker these days, I think its significant. To me, calling JSON.ArrayConcat makes it look like we are calling the ArrayConcat property or method of the JSON object. That's not what we're doing so I think this potential confusion should be avoided. I'm thinking of FileMaker systems that may use or generate JavaScript code. FileMaker code in these systems should not appear to imitating JavaScript code.

**Comment by toddgeist** [comment]
Thanks for the feedback.  It's worth considering.

We do a ton of Code Generation right now with these functions and other things name spaced with a dot. And we do not have really have this issue, so I don't think thats a real issue.  Do you have an example where this is a problem?

Number 2 might be a good reason. But it doesn't always hold true in JavaScript. 

For ex
```
Object.keys(variable) // gets the properties of the variable
Array.isArray(arrayVariable) // tells you if the variable is an array
```
These are Static Methods on the Object object and the Array object respectively.  To me that is similar to what we are doing

JSON.ArrayConcat could be a Static Method which is pretty much what it is.

I am not altogether opposed to the idea however. It's just that changing these names is considerable work, and unless it has a true value, I am going to want to push it down the list of priorities

**Comment by alecgregory** [comment]
Point well-taken on static methods, I understand the naming a bit better with that in mind. I think we can safely assume people won't be trying to add "methods" to custom functions the JavaScript way (yet, though it would be kinda awesome if you could extend in that way)

Right now I don't have a real example of where it's a problem but I can give you a theoretical one. Imagine a FileMaker system that parses custom functions from a DDR snippet and analyzes them for differences. To do this it holds the custom functions in a JSON object:
```
{
  "JSON.ArrayConcat" : "Custom function code",
  "JSON.ArrayFromRelated" : "Custom function code"
}
```

You won't be able to access items in this object using JSONGetElement

Now it's not the end of the world. You can change your object to an array of objects

```
[
  {
    "functionName" : "JSON.ArrayConcat"
    "code" : "Custom function code"
  },
  {
    "functionName" : "JSON.ArrayFromRelated"
    "code" : "Custom function code"
  }
}
```

And for sure the second implementation is more robust, but it's also leads to a more complex structure that's a bit harder to navigate. So I guess the question is do we want to try to help developers out by being making the naming as permissive as possible or trusting them to implement robust solutions that can handle the issues the naming can introduce?

**Comment by toddgeist** [comment]
Its a good point.  But I think the tools that do the kinds of analysis you are describing will probably be able to handle the simple work-a-arounds to make that work.  

As usual it's never a question of what to do, It's when to do it.  And this still seems pretty low down the list

**Comment by alecgregory** [comment]
Understood. I feel it's something that could become more or less relevant depending on how the FileMaker platforms evolves. And I suppose it's not a good idea to make big changes based on other systems private development plans.

**Comment by toddgeist** [comment]
closing for now
