### ISSUE TITLE
Replace literal field name references with rename-safe alternatives

### ISSUE THREAD

**Issue by alecgregory** [karbonfm/karbonfm#35]
Instead of using literal field references which will may cause breakages if fields are renamed, it might be better to use a custom function to generate dynamic strings that will change when field names are changed:

The example below comes from the AsJSON field in the ActivityParty table.

```
JSONSetElement ( "{}" ; 
	[ "ActivityId" ; ActivityId ; JSONString ];
	[ "ActivityPartyRoleId" ; ActivityPartyRoleId ; JSONString ];
	[ "ContactMethodId" ; ContactMethodId ; JSONString ];
	[ "Id" ; Id ; JSONString ];
	[ "NotificationSentInd" ; NotificationSentInd ; JSONString ];
	[ "PartyId" ; PartyId ; JSONString ]
)
```
would become
```
JSONSetElement ( "{}" ; 
	[ FM.GetFieldName ( ActivityId ) ; ActivityId ; JSONString ];
	[ FM.GetFieldName ( ActivityPartyRoleId ) ; ActivityPartyRoleId ; JSONString ];
	[ FM.GetFieldName ( ContactMethodId ) ; ContactMethodId ; JSONString ];
	[ FM.GetFieldName ( Id ) ; Id ; JSONString ];
	[ FM.GetFieldName ( NotificationSentInd ) ; NotificationSentInd ; JSONString ];
	[ FM.GetFieldName ( PartyId ) ; PartyId ; JSONString ]
)
```
Using the custom function
```
/**
 * 
 * get the local field name from a field reference
 *
 * @param {reference} field
 *
 * @returns {string} 
 *
 * @module rename-tolerant demo
 * 
 * @history  2018-09-18, 
 * 
 * @notes only works if the field is in context
 *
 */

GetValue (
	Substitute (
		GetFieldName ( field );
		"::";
		¶
	);
	2
)
```

Attached is a file that demonstrates the rename-safe technique in the ActivityParty Table. It has the FM.GetFieldName custom function included
[karbon_data.fmp12.zip](https://github.com/karbonfm/karbonfm/files/2402667/karbon_data.fmp12.zip)

**Comment by davegraham92120** [comment]
We are intentionally not abstracting the field names. Once the object is in JSON and other services are consuming that JSON, they need a reliable JSON keys. If the JSON key name changes with the field name, you will have downstream scripts breaking every time a field is renamed.

**Comment by toddgeist** [comment]
not just scripts but anything else that uses those API, Like web services, web pages etc. would all break.

**Comment by alecgregory** [comment]
I see, I look at it a different (opposite?) way. I want those things to break in development to maintain consistency. Once you have a production version of a system in the wild you have to consider the implications of changing field names anyway so I don't see it as a big problem.

**Comment by davegraham92120** [comment]
The nice thing about Karbon is that you can have it both ways. You can write two AsJson calcs, one with static keys and another with dynamic keys. Then you can choose to use one or the other based on your use-case. :-)

**Comment by alecgregory** [comment]
That’s true! Perhaps multiple hard-coded fields could even be versioned and then compared against the dynamic one.

Thanks.
