### ISSUE TITLE
Warn if user profile isn't linked to a party

### ISSUE THREAD

**Issue by davegraham92120** [karbonfm/karbonfm#38]
If there is no party associated with a user, the user should be warned that their profile is incomplete. Many tasks require a party ID (e.g., create activity).

**Comment by bcooney93** [comment]
Is this still an issue since I see that we create a Party if necessary in the Create User API.

**Comment by bcooney93** [comment]
We could add a warning to Store UserID On Session if PartyId is missing.

**Comment by bcooney93** [comment]
Added SCD to _Store UserID on Session_ if PartyId is missing.
