### ISSUE TITLE
New contact wizard: org name entered in card should perform Google Places search

### ISSUE THREAD

**Issue by davegraham92120** [karbonfm/karbonfm#42]
When you enter a company name here and click the Lookup… button...

![screen shot 2018-10-12 at 8 21 06 am](https://user-images.githubusercontent.com/20668953/46878307-c9bca600-cdf7-11e8-8115-dc33612b6f94.png)

The company name should be transferred to the search box, the search should default to Google Places, and the search should be executed

**Comment by bcooney93** [comment]
Ready to review.
