### ISSUE TITLE
Add phone extension field to new contact wizard

### ISSUE THREAD

**Issue by davegraham92120** [karbonfm/karbonfm#43]
We need to add the phone extension as a separate field for both the company and person slides.

![screen shot 2018-10-12 at 8 25 46 am](https://user-images.githubusercontent.com/20668953/46878550-73039c00-cdf8-11e8-8ec6-3e971e2bf597.png)

**Comment by bcooney93** [comment]
Do you think that Organizations should have phone extensions? Seems like a Person attribute only.

**Comment by bcooney93** [comment]
Also, you cache Phone in Party. Do you want to add a cache field for Extension?

**Comment by davegraham92120** [comment]
Good point. Extension should apply only to a person for now.

Dave

**Comment by davegraham92120** [comment]
We should add the extension to the phone when we cache it.

Dave

**Comment by bcooney93** [comment]
![image](https://user-images.githubusercontent.com/42422435/46886044-b3c6d980-ce27-11e8-8407-14977341eb89.png)

**Comment by davegraham92120** [comment]
Looks good, but please include the extension label (e.g., " ext. " & Phone::Extension)
