### ISSUE TITLE
Create dedicated find layout for the Opportunity Detail

### ISSUE THREAD

**Issue by davegraham92120** [karbonfm/karbonfm#44]
This is a mess. We should create a dedicated find layout for opportunities. 

![screen shot 2018-10-12 at 9 34 43 am](https://user-images.githubusercontent.com/20668953/46882032-2ae97700-ce02-11e8-8be7-849d165e7ab7.png)

**Comment by bcooney93** [comment]
Started on this Dave, created a dedicated layout "Opportunity Find." Would like to chat with you about Find functionality in general.
