### ISSUE TITLE
Add default custom menu that excludes delete all records

### ISSUE THREAD

**Issue by davegraham92120** [karbonfm/karbonfm#47]
Delete All Records should not be allowed by default.

**Comment by bcooney93** [comment]
I have removed Find/Replace in that past. Do that as well?

**Comment by davegraham92120** [comment]
sure

**Comment by bcooney93** [comment]
Alrighty, so how do you want to load the new limited User Menu Set? System Startup script, I'd presume.  

![image](https://user-images.githubusercontent.com/42422435/46888149-a4e32580-ce2d-11e8-84c2-f68807364abc.png)

**Comment by davegraham92120** [comment]
![screen shot 2018-10-12 at 12 20 40 pm](https://user-images.githubusercontent.com/20668953/46889696-6c395100-ce19-11e8-8aa5-a40269cac64d.png)

**Comment by bcooney93** [comment]
Ha! I didn't think you'd want to use that. We'd be fighting that as developers.

**Comment by bcooney93** [comment]
Set User Menu set as file default, but set Standard if full access.
