### ISSUE TITLE
Clean text on all relevant utility and contact fields

### ISSUE THREAD

**Issue by davegraham92120** [karbonfm/karbonfm#48]
We should be stripping spaces and formatting from nearly every utility field, as well as all party-related fields (e.g., first name, last name). 

Please use this function: CleanText ( Self )

Make sure that "Do not evaluate…" and "Do not replace…" boxes are un-checked 

![screen shot 2018-10-12 at 9 54 33 am](https://user-images.githubusercontent.com/20668953/46882807-d7c4f380-ce04-11e8-8cf8-1c1eddc4a5bd.png)

**Comment by bcooney93** [comment]
![image](https://user-images.githubusercontent.com/42422435/46883071-c7217700-ce1e-11e8-9d71-62d6af8d6b28.png)

**Comment by davegraham92120** [comment]
@bcooney93 - did you have a question?

**Comment by bcooney93** [comment]
confirming what you meant by Utility fields. Those in Utility tables, correct?

**Comment by davegraham92120** [comment]
Yep.

Dave

**Comment by bcooney93** [comment]
Used FMP to find all uses of Trim4, and came across this calc in Phone table. Is this abandoned since your use of Twilio? Do we need to use CleanText here?

![image](https://user-images.githubusercontent.com/42422435/46883620-a528f400-ce20-11e8-9ae9-3670d6afebd2.png)

**Comment by davegraham92120** [comment]
Yes, it is legacy. Please remove.

Dave

**Comment by davegraham92120** [comment]
Please don't close any GH issue until you've logged it in Karbon build!

**Comment by bcooney93** [comment]
Oops.
