### ISSUE TITLE
JSON.ArrayFromRelated Returns blank for a single related record

### ISSUE THREAD

**Issue by alecgregory** [karbonfm/karbonfm#52]
When there is only 1 related record the JSON.ArrayFromRelated custom function returns blank. I think this is because the list function doesn't accept single values as a parameter. To fix you can add an extra blank string parameter after to the List function:

```
"[" & 

Substitute(
    List(JSONField; "") ; 
    "¶" ; ","
)

& 

"]"

**Comment by davegraham92120** [comment]
You sure you were pulling a related value and not a local value? It works fine for me when there is only one related value. 

[Array From Related.fmp12.zip](https://github.com/karbonfm/karbonfm/files/2485335/Array.From.Related.fmp12.zip)
