### ISSUE TITLE
Opportunity list view enhancements

### ISSUE THREAD

**Issue by davegraham92120** [karbonfm/karbonfm#55]
Can you please make the following changes? 

![screen shot 2018-10-19 at 9 07 28 am](https://user-images.githubusercontent.com/20668953/47230300-bf158a00-d37e-11e8-9ccf-19307b7c8363.png)

I want to be able to see at a glance what the next step is for every opportunity.

**Comment by bcooney93** [comment]
Next task is?
Look thru relationship to Activity where TaskInd =1 and Completed<>1?

**Comment by davegraham92120** [comment]
I've added the relationship

**Comment by bcooney93** [comment]
OK, adjusted the anchors and logged in Build.
