### ISSUE TITLE
Create Network Address not setting EmailAddressInd

### ISSUE THREAD

**Issue by davegraham92120** [karbonfm/karbonfm#57]
Default to true if we think it's an email address.

**Comment by davegraham92120** [comment]
Moved logic from auto-enter calc to scripts in kontroller (new addresses) and UI (existing). We should move all logic to kontroller eventually.

**Comment by mr-scott** [comment]
It would be great to document these types of efforts - moving logic from schema to controller, for others to learn from.

**Comment by davegraham92120** [comment]
> It would be great to document these types of efforts - moving logic from schema to controller, for others to learn from.

Yep. This will be covered in future webinars and blog posts that dive into the scripting approach.
