### ISSUE TITLE
Activity AsJson uses old-style parent object

### ISSUE THREAD

**Issue by davegraham92120** [karbonfm/karbonfm#58]
The format for the activity table AsJson looks like this: 

{
	"Activity" : 
	{
		"ActivityGroupId" : "",
		"ActivityParentID" : "",
		"ActivityParty" :  [],
		...
	}
}

We are no longer creating a parent level object, which just makes the object harder to parse. I've created a V2 of this field; we need to trace all dependencies to V1, and ensure they will work with V2 before updating references.

**Comment by bcooney93** [comment]
Not seeing any references that relied on parsing the Activity::AsJSON field. Does that seem odd to you?

**Comment by davegraham92120** [comment]
Nope

**Comment by bcooney93** [comment]
All FMPerception found were 3 scripts in kontroller that returned that field as a result.
