### ISSUE TITLE
Tasks on home layout needs related entity functionality

### ISSUE THREAD

**Issue by davegraham92120** [karbonfm/karbonfm#59]
We need to see the linked entity and a button to go to the entity.

![screen shot 2018-10-26 at 8 37 54 am](https://user-images.githubusercontent.com/20668953/47576932-86cff780-d8fa-11e8-8947-1031be810da7.png)

**Comment by bcooney93** [comment]
Interesting..are tasks for UserIds or PartyIds? Seems that it's PartyId. So, each user needs a Party record.

**Comment by davegraham92120** [comment]
Activities are created by user IDs, but need a relationship to a party for everything meaningful. All regular users (e.g., not bots) must have a party record in order to fully utilize Karbon. That's the reason for GH#38.
