### ISSUE TITLE
Need new activity subtype "Call"

### ISSUE THREAD

**Issue by davegraham92120** [karbonfm/karbonfm#60]
Similar to note, but with call-specific functionality: 
- Caller name (may not exist in the database)
- Callback number
- Result (e.g., left message, no answer)

Will be used to measure call activity in a sales environment.

**Comment by bcooney93** [comment]
Ready for review. A bit unclear the distinction between Message and Result.

**Comment by davegraham92120** [comment]
Are you referring to ActivityMessage::Message? That's the full activity body, which is different for different activities. For Letter and EmailMessage, it's the body of the Activity. For all others, it's a comment/description field.
