### ISSUE TITLE
Upload files by ID instead of Base64 encoding

### ISSUE THREAD

**Issue by davegraham92120** [karbonfm/karbonfm#64]
- Insert a reference to a local (UI file) global container
- Pass reference to API. API will insert the file based on the path into File::Container (container field will need to exist on DBTransactions layout)
- Add max file attachment size and rule for API

**Comment by bcooney93** [comment]
"(container field will need to exist on DBTransactions layout)"  - didn't seem to be.

**Comment by davegraham92120** [comment]
@bcooney93 - it will be if you add it. ;-)

**Comment by bcooney93** [comment]
What I meant was that a container on DBTran didn't seem to be needed. Let's review this.

**Comment by bcooney93** [comment]
As far as I can tell, we can simply passing the API a path to the file.
