### ISSUE TITLE
Cache customer balance due and retainer balance

### ISSUE THREAD

**Issue by davegraham92120** [karbonfm/karbonfm#69]
The Customer list view is way too slow. Please ensure that the unstored calc fields on this layout are cached during QBO syncing.

**Comment by bcooney93** [comment]
RetainerBalance is unstored, and I've added a RetainerBalanceCached. The cache is set in Post/Unpost Sales Transaction "Post/Unpost Internal ( {Id, Post} )". To be decided, deprecate the unstored field.

**Comment by davegraham92120** [comment]
The purpose of the field hasn't changed; we probably don't want to create a new field for a change in storage.

**Comment by bcooney93** [comment]
OK, changed the field definition to number, and we now set that field in Post/Unpost. We'll also need to script edits to Retainer Adjustment (which is not exposed yet in the UI).
