### ISSUE TITLE
Customer search is way too slow

### ISSUE THREAD

**Issue by davegraham92120** [karbonfm/karbonfm#70]
Not sure if the standard find on the Customer list view is using Quick Find, but it's way too slow.

**Comment by bcooney93** [comment]
Not seeing the performance issue. Yes, the standard find is a QuickFind.

**Comment by davegraham92120** [comment]
Try it on the production server. :-)

**Comment by bcooney93** [comment]
Yikes. I see what you mean.

**Comment by bcooney93** [comment]
Seems like it just needed an index. Quite performant now.
