### ISSUE TITLE
Update

### ISSUE THREAD

**Issue by luigithekid** [karbonfm/karbonfm#71]
I saw the video with logging, when are you guys updating the files with that functionality (even if pre-alpha)?
Also, on the webinar, the karbon_dev file had all the links to all the other files, is this something you guys will be sharing as well?

**Comment by davegraham92120** [comment]
Very soon. Yes, karbon_dev will be included.

**Comment by davegraham92120** [comment]
Trying to get through these bugs before the next release. Please feel free to post questions and discuss Karbon in our forum. https://discourse.karbon.fm
