### ISSUE TITLE
Delete Contact Methods - Dialog Error

### ISSUE THREAD

**Issue by laynebay** [karbonfm/karbonfm#72]
For Contact Methods - Button: Delete Phone, Button: Delete Network Address, Button: Delete Address...
Dialog references the wrong variable.

`If [ Error.IsError ( $result ) ]`
       `Set Variable [ $message ; Value: JSONGetElement ( $result ; "errorMessage" ) ]`
       `Show Custom Dialog [ "Error" ; "An error occurred: " & $errorMessage & "." ]`
`End If`

BTW - I've learned a ton going through Karbon. Thanks @toddgeist , @davegraham92120

**Comment by toddgeist** [comment]
Thanks :-)

**Comment by bcooney93** [comment]
fixed
