### ISSUE TITLE
Welcome wizard error

### ISSUE THREAD

**Issue by davegraham92120** [karbonfm/karbonfm#74]
The wizard attempts to create a party relation that already exists. Check to see if it's being created when the employee or user is created.

**Comment by bcooney93** [comment]
the party relationship is created by the Employee API

**Comment by davegraham92120** [comment]
I'm pretty sure I already fixed this. Check the build log and mark this closed if it's done.

**Comment by davegraham92120** [comment]
@bcooney93 - please update this

**Comment by bcooney93** [comment]
Yep, there's a entry in the build log from 2/6/19 by you for this fix: "We no longer need to create employee/company relationships in the Welcome Wizard; it's handled by the Create Employee API"
