### ISSUE TITLE
Add back/forward keyboard shortcuts

### ISSUE THREAD

**Issue by davegraham92120** [karbonfm/karbonfm#87]
We need keyboard shortcuts for global back/forward nav. Cmd/Ctrl+arrow key

**Comment by bcooney93** [comment]
not sure what modifier to use for Windows. Help seems to indicate that Ctrl and (or?) Alt cannot be used to fire a trigger.

**Comment by davegraham92120** [comment]
@bcooney93 - Please use custom menus instead of triggers

**Comment by davegraham92120** [comment]
Done
