### ISSUE TITLE
Discussion Subscribers: Optimizing the selection process

### ISSUE THREAD

**Issue by bcooney93** [karbonfm/karbonfm#90]
Similar to Basecamp, pre-populate the Picker party list with parties associated with the current entity. Provide a toggle at the top of the discussion: Internal or External Stakeholders. Change button to "Manage Subscribers."

Also, select existing subscribers in the picker. Deselecting them will remove them from the discussion.

**Comment by bcooney93** [comment]
Dave, the toggle: Internal or External Stakeholders" .. I believe that is a parent Activity field. Do you agree? "Who is allowed to discuss this activity?"

**Comment by davegraham92120** [comment]
@jlbmagic was talking about doing this in a widget. Adding him to this thread.

**Comment by jlbmagic** [comment]
Here are two possibilities:
![2019-06-20_18-59-22](https://user-images.githubusercontent.com/20194907/59886593-9c17fb80-938d-11e9-8b4d-0174369902d2.png)
![2019-06-20_18-59-33](https://user-images.githubusercontent.com/20194907/59886596-9de1bf00-938d-11e9-8941-e5885e21a334.png)
[SearchBars.fmp12.zip](https://github.com/karbonfm/karbonfm/files/3312341/SearchBars.fmp12.zip)

There's lots of options in the two versions I have.
You simply load the search terms in the proper format (see $data variable) and they're available.

**Comment by jlbmagic** [comment]
Ok.Here's the better one. Fixed the silly return values. It returns an array of the objects of the records selected.
[New_SearchBars.fmp12.zip](https://github.com/karbonfm/karbonfm/files/3322614/New_SearchBars.fmp12.zip)

**Comment by davegraham92120** [comment]
We're closing this and creating separate tasks for individual issues.
